language: node_js
node_js:
      - "5"
      - "6"
      - "7"
cache: yarn
script:
      - yarn install --cwd examples/async
      - yarn install --cwd site
      - yarn run build
      - yarn run test:cov
after_success:
      - yarn run coverage
